// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoEF.Context;

#nullable disable

namespace proyectoEF.Migrations
{
    [DbContext(typeof(TareasContext))]
    partial class TareasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyectoEF.Modelo.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("720f08a5-0b57-488a-af5f-8913c8535da6"),
                            Descripcion = "Actividades Pendientes de realizar",
                            Nombre = "Actividades Pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("f0a66bcd-8a6a-4ba3-a77b-fd87987132b4"),
                            Descripcion = "Actividades personales a realizar",
                            Nombre = "Actividades Personales",
                            Peso = 20
                        });
                });

            modelBuilder.Entity("proyectoEF.Modelo.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("369b68d6-e4b6-48c2-a232-7cf6f8bd736c"),
                            CategoriaId = new Guid("720f08a5-0b57-488a-af5f-8913c8535da6"),
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 2, 27, 23, 32, 57, 21, DateTimeKind.Local).AddTicks(6483),
                            Prioridad = 1,
                            Titulo = "Tareas Pendientes"
                        },
                        new
                        {
                            TareaId = new Guid("0d24f6be-ad17-4d7c-87f1-1e5950838680"),
                            CategoriaId = new Guid("f0a66bcd-8a6a-4ba3-a77b-fd87987132b4"),
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 2, 27, 23, 32, 57, 21, DateTimeKind.Local).AddTicks(6496),
                            Prioridad = 0,
                            Titulo = "Tareas Personales"
                        });
                });

            modelBuilder.Entity("proyectoEF.Modelo.Tarea", b =>
                {
                    b.HasOne("proyectoEF.Modelo.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyectoEF.Modelo.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
